image: mcr.microsoft.com/dotnet/sdk:9.0

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - when: never

stages:
  - build
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_NOLOGO: "true"

before_script:
  - dotnet restore src/ArgParser.sln

build:
  stage: build
  script:
    - dotnet build src/ArgParser.sln --configuration Release --no-restore
  artifacts:
    paths:
      - cli-parser/bin/
      - cli-parser/obj/
      - tests/bin/
      - tests/obj/

test:
  stage: test
  needs:
    - job: build
      artifacts: true
  script:
    - dotnet test CliParserSolution.sln --configuration Release --no-build --no-restore