stages:
  - build
  - test

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - dotnet build tests/ArgParserTests/ArgParserTests.csproj --configuration Release

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - dotnet test tests/ArgParserTests/ArgParserTests.csproj --configuration Release