image: mcr.microsoft.com/dotnet/sdk:9.0

stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet restore src/ArgParser.sln
    - dotnet publish src/ArgParser.sln -c Release -o out/
  artifacts:
    paths:
      - out/
    expire_in: 1 hour

tests:
  stage: test
  dependencies:
    - build
  script:
    - dotnet test out/APITests.dll
    - dotnet test out/ArgParserTests.dll
